/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as NotesIndexRouteImport } from './routes/notes/index'
import { Route as FragrancesIndexRouteImport } from './routes/fragrances/index'
import { Route as AccordsIndexRouteImport } from './routes/accords/index'
import { Route as UserIdRouteImport } from './routes/user/$id'
import { Route as AuthAccountRecoveryRouteImport } from './routes/auth/account-recovery'
import { Route as UserIdIndexRouteImport } from './routes/user/$id/index'
import { Route as NewFragranceIndexRouteImport } from './routes/new/fragrance/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const FragrancesIndexRoute = FragrancesIndexRouteImport.update({
  id: '/fragrances/',
  path: '/fragrances/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordsIndexRoute = AccordsIndexRouteImport.update({
  id: '/accords/',
  path: '/accords/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountRecoveryRoute = AuthAccountRecoveryRouteImport.update({
  id: '/auth/account-recovery',
  path: '/auth/account-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserIdRoute,
} as any)
const NewFragranceIndexRoute = NewFragranceIndexRouteImport.update({
  id: '/new/fragrance/',
  path: '/new/fragrance/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/account-recovery': typeof AuthAccountRecoveryRoute
  '/user/$id': typeof UserIdRouteWithChildren
  '/accords': typeof AccordsIndexRoute
  '/fragrances': typeof FragrancesIndexRoute
  '/notes': typeof NotesIndexRoute
  '/user': typeof UserIndexRoute
  '/new/fragrance': typeof NewFragranceIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/account-recovery': typeof AuthAccountRecoveryRoute
  '/accords': typeof AccordsIndexRoute
  '/fragrances': typeof FragrancesIndexRoute
  '/notes': typeof NotesIndexRoute
  '/user': typeof UserIndexRoute
  '/new/fragrance': typeof NewFragranceIndexRoute
  '/user/$id': typeof UserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/account-recovery': typeof AuthAccountRecoveryRoute
  '/user/$id': typeof UserIdRouteWithChildren
  '/accords/': typeof AccordsIndexRoute
  '/fragrances/': typeof FragrancesIndexRoute
  '/notes/': typeof NotesIndexRoute
  '/user/': typeof UserIndexRoute
  '/new/fragrance/': typeof NewFragranceIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/account-recovery'
    | '/user/$id'
    | '/accords'
    | '/fragrances'
    | '/notes'
    | '/user'
    | '/new/fragrance'
    | '/user/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/account-recovery'
    | '/accords'
    | '/fragrances'
    | '/notes'
    | '/user'
    | '/new/fragrance'
    | '/user/$id'
  id:
    | '__root__'
    | '/'
    | '/auth/account-recovery'
    | '/user/$id'
    | '/accords/'
    | '/fragrances/'
    | '/notes/'
    | '/user/'
    | '/new/fragrance/'
    | '/user/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthAccountRecoveryRoute: typeof AuthAccountRecoveryRoute
  UserIdRoute: typeof UserIdRouteWithChildren
  AccordsIndexRoute: typeof AccordsIndexRoute
  FragrancesIndexRoute: typeof FragrancesIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
  UserIndexRoute: typeof UserIndexRoute
  NewFragranceIndexRoute: typeof NewFragranceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragrances/': {
      id: '/fragrances/'
      path: '/fragrances'
      fullPath: '/fragrances'
      preLoaderRoute: typeof FragrancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accords/': {
      id: '/accords/'
      path: '/accords'
      fullPath: '/accords'
      preLoaderRoute: typeof AccordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account-recovery': {
      id: '/auth/account-recovery'
      path: '/auth/account-recovery'
      fullPath: '/auth/account-recovery'
      preLoaderRoute: typeof AuthAccountRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/'
      fullPath: '/user/$id/'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof UserIdRoute
    }
    '/new/fragrance/': {
      id: '/new/fragrance/'
      path: '/new/fragrance'
      fullPath: '/new/fragrance'
      preLoaderRoute: typeof NewFragranceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UserIdRouteChildren {
  UserIdIndexRoute: typeof UserIdIndexRoute
}

const UserIdRouteChildren: UserIdRouteChildren = {
  UserIdIndexRoute: UserIdIndexRoute,
}

const UserIdRouteWithChildren =
  UserIdRoute._addFileChildren(UserIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthAccountRecoveryRoute: AuthAccountRecoveryRoute,
  UserIdRoute: UserIdRouteWithChildren,
  AccordsIndexRoute: AccordsIndexRoute,
  FragrancesIndexRoute: FragrancesIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
  UserIndexRoute: UserIndexRoute,
  NewFragranceIndexRoute: NewFragranceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
